// Generated by HEXA self-host compiler
#include "runtime.c"

HexaVal is_keyword(HexaVal word);
HexaVal keyword_kind(HexaVal word);
HexaVal is_ident_start(HexaVal ch);
HexaVal is_ident_char(HexaVal ch);
HexaVal tokenize(HexaVal source);
HexaVal count_kind(HexaVal tokens, HexaVal kind);


HexaVal Token(HexaVal kind, HexaVal value, HexaVal line, HexaVal col) {
    HexaVal __s = hexa_map_new();
    __s = hexa_map_set(__s, "__type__", hexa_str("Token"));
    __s = hexa_map_set(__s, "kind", kind);
    __s = hexa_map_set(__s, "value", value);
    __s = hexa_map_set(__s, "line", line);
    __s = hexa_map_set(__s, "col", col);
    return __s;
}


HexaVal is_keyword(HexaVal word) {
    if (hexa_truthy(hexa_eq(word, hexa_str("if")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("else")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("match")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("for")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("while")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("loop")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("type")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("struct")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("enum")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("trait")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("impl")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("fn")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("return")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("yield")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("async")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("await")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("let")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("mut")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("const")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("static")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("mod")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("use")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("import")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("pub")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("crate")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("own")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("borrow")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("move")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("drop")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("spawn")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("channel")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("select")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("atomic")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("effect")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("handle")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("resume")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("pure")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("proof")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("assert")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("invariant")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("theorem")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("macro")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("derive")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("where")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("comptime")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("try")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("catch")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("throw")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("panic")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("recover")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("intent")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("generate")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("verify")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("optimize")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("extern")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("break")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("continue")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("dyn")))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("scope")))) {
        return hexa_bool(1);
    }
    return hexa_bool(0);
    return hexa_void();
}


HexaVal keyword_kind(HexaVal word) {
    if (hexa_truthy(hexa_eq(word, hexa_str("true")))) {
        return hexa_str("BoolLit");
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("false")))) {
        return hexa_str("BoolLit");
    }
    if (hexa_truthy(hexa_eq(word, hexa_str("import")))) {
        return hexa_str("Use");
    }
    if (hexa_truthy(is_keyword(word))) {
        HexaVal first = hexa_str_to_upper(hexa_to_string(hexa_index_get(hexa_str_chars(word), hexa_int(0))));
        HexaVal rest = hexa_str("");
        HexaVal chars = hexa_str_chars(word);
        HexaVal i = hexa_int(1);
        while (hexa_truthy(hexa_bool((i).i < (hexa_int(hexa_len(chars))).i))) {
            rest = hexa_add(rest, hexa_to_string(hexa_index_get(chars, i)));
            i = hexa_add(i, hexa_int(1));
        }
        return hexa_add(first, rest);
    }
    return hexa_str("Ident");
    return hexa_void();
}


HexaVal is_ident_start(HexaVal ch) {
    if (hexa_truthy(hexa_bool((ch.tag==TAG_STR && ch.s && isalpha((unsigned char)ch.s[0])) || (ch.tag==TAG_CHAR && isalpha((unsigned char)ch.i))))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(ch, hexa_str("_")))) {
        return hexa_bool(1);
    }
    return hexa_bool(0);
    return hexa_void();
}


HexaVal is_ident_char(HexaVal ch) {
    if (hexa_truthy(hexa_bool((ch.tag==TAG_STR && ch.s && isalnum((unsigned char)ch.s[0])) || (ch.tag==TAG_CHAR && isalnum((unsigned char)ch.i))))) {
        return hexa_bool(1);
    }
    if (hexa_truthy(hexa_eq(ch, hexa_str("_")))) {
        return hexa_bool(1);
    }
    return hexa_bool(0);
    return hexa_void();
}


HexaVal tokenize(HexaVal source) {
    HexaVal tokens = hexa_array_new();
    HexaVal chars = hexa_str_chars(source);
    HexaVal pos = hexa_int(0);
    HexaVal line = hexa_int(1);
    HexaVal col = hexa_int(1);
    HexaVal total = hexa_int(hexa_len(chars));
    while (hexa_truthy(hexa_bool((pos).i < (total).i))) {
        HexaVal ch = hexa_index_get(chars, pos);
        if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool(hexa_truthy(hexa_eq(ch, hexa_str(" "))) || hexa_truthy(hexa_eq(ch, hexa_str("\t"))))) || hexa_truthy(hexa_eq(ch, hexa_str("\r")))))) {
            pos = hexa_add(pos, hexa_int(1));
            col = hexa_add(col, hexa_int(1));
        } else {
            if (hexa_truthy(hexa_eq(ch, hexa_str("\n")))) {
                tokens = hexa_array_push(tokens, Token(hexa_str("Newline"), hexa_str("\n"), line, col));
                pos = hexa_add(pos, hexa_int(1));
                line = hexa_add(line, hexa_int(1));
                col = hexa_int(1);
            } else {
                if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool(hexa_truthy(hexa_eq(ch, hexa_str("/"))) && hexa_truthy(hexa_bool((hexa_add(pos, hexa_int(1))).i < (total).i)))) && hexa_truthy(hexa_eq(hexa_index_get(chars, hexa_add(pos, hexa_int(1))), hexa_str("/")))))) {
                    pos = hexa_add(pos, hexa_int(2));
                    col = hexa_add(col, hexa_int(2));
                    while (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((pos).i < (total).i)) && hexa_truthy(hexa_bool(!hexa_truthy(hexa_eq(hexa_index_get(chars, pos), hexa_str("\n")))))))) {
                        pos = hexa_add(pos, hexa_int(1));
                        col = hexa_add(col, hexa_int(1));
                    }
                } else {
                    if (hexa_truthy(is_ident_start(ch))) {
                        HexaVal start_col = col;
                        HexaVal word = hexa_str("");
                        while (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((pos).i < (total).i)) && hexa_truthy(is_ident_char(hexa_index_get(chars, pos)))))) {
                            word = hexa_add(word, hexa_to_string(hexa_index_get(chars, pos)));
                            pos = hexa_add(pos, hexa_int(1));
                            col = hexa_add(col, hexa_int(1));
                        }
                        HexaVal kind = keyword_kind(word);
                        tokens = hexa_array_push(tokens, Token(kind, word, line, start_col));
                    } else {
                        if (hexa_truthy(hexa_bool((ch.tag==TAG_STR && ch.s && isdigit((unsigned char)ch.s[0])) || (ch.tag==TAG_CHAR && isdigit((unsigned char)ch.i))))) {
                            HexaVal start_col = col;
                            HexaVal num_str = hexa_str("");
                            HexaVal is_float = hexa_bool(0);
                            while (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((pos).i < (total).i)) && hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_index_get(chars, pos).tag==TAG_STR && hexa_index_get(chars, pos).s && isdigit((unsigned char)hexa_index_get(chars, pos).s[0])) || (hexa_index_get(chars, pos).tag==TAG_CHAR && isdigit((unsigned char)hexa_index_get(chars, pos).i)))) || hexa_truthy(hexa_eq(hexa_index_get(chars, pos), hexa_str("_")))))))) {
                                if (hexa_truthy(hexa_eq(hexa_index_get(chars, pos), hexa_str("_")))) {
                                    pos = hexa_add(pos, hexa_int(1));
                                    col = hexa_add(col, hexa_int(1));
                                } else {
                                    num_str = hexa_add(num_str, hexa_to_string(hexa_index_get(chars, pos)));
                                    pos = hexa_add(pos, hexa_int(1));
                                    col = hexa_add(col, hexa_int(1));
                                }
                            }
                            if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((pos).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, pos), hexa_str(".")))))) {
                                if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_add(pos, hexa_int(1))).i < (total).i)) && hexa_truthy(hexa_bool((hexa_index_get(chars, hexa_add(pos, hexa_int(1))).tag==TAG_STR && hexa_index_get(chars, hexa_add(pos, hexa_int(1))).s && isdigit((unsigned char)hexa_index_get(chars, hexa_add(pos, hexa_int(1))).s[0])) || (hexa_index_get(chars, hexa_add(pos, hexa_int(1))).tag==TAG_CHAR && isdigit((unsigned char)hexa_index_get(chars, hexa_add(pos, hexa_int(1))).i))))))) {
                                    is_float = hexa_bool(1);
                                    num_str = hexa_add(num_str, hexa_str("."));
                                    pos = hexa_add(pos, hexa_int(1));
                                    col = hexa_add(col, hexa_int(1));
                                    while (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((pos).i < (total).i)) && hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_index_get(chars, pos).tag==TAG_STR && hexa_index_get(chars, pos).s && isdigit((unsigned char)hexa_index_get(chars, pos).s[0])) || (hexa_index_get(chars, pos).tag==TAG_CHAR && isdigit((unsigned char)hexa_index_get(chars, pos).i)))) || hexa_truthy(hexa_eq(hexa_index_get(chars, pos), hexa_str("_")))))))) {
                                        if (hexa_truthy(hexa_eq(hexa_index_get(chars, pos), hexa_str("_")))) {
                                            pos = hexa_add(pos, hexa_int(1));
                                            col = hexa_add(col, hexa_int(1));
                                        } else {
                                            num_str = hexa_add(num_str, hexa_to_string(hexa_index_get(chars, pos)));
                                            pos = hexa_add(pos, hexa_int(1));
                                            col = hexa_add(col, hexa_int(1));
                                        }
                                    }
                                }
                            }
                            if (hexa_truthy(is_float)) {
                                tokens = hexa_array_push(tokens, Token(hexa_str("FloatLit"), num_str, line, start_col));
                            } else {
                                tokens = hexa_array_push(tokens, Token(hexa_str("IntLit"), num_str, line, start_col));
                            }
                        } else {
                            if (hexa_truthy(hexa_eq(ch, hexa_str("\"")))) {
                                HexaVal start_col = col;
                                pos = hexa_add(pos, hexa_int(1));
                                col = hexa_add(col, hexa_int(1));
                                HexaVal s = hexa_str("");
                                HexaVal done = hexa_bool(0);
                                while (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((pos).i < (total).i)) && hexa_truthy(hexa_bool(!hexa_truthy(done)))))) {
                                    HexaVal c = hexa_index_get(chars, pos);
                                    if (hexa_truthy(hexa_eq(c, hexa_str("\"")))) {
                                        done = hexa_bool(1);
                                        pos = hexa_add(pos, hexa_int(1));
                                        col = hexa_add(col, hexa_int(1));
                                    } else {
                                        if (hexa_truthy(hexa_eq(c, hexa_str("\\")))) {
                                            pos = hexa_add(pos, hexa_int(1));
                                            col = hexa_add(col, hexa_int(1));
                                            if (hexa_truthy(hexa_bool((pos).i < (total).i))) {
                                                HexaVal esc = hexa_index_get(chars, pos);
                                                if (hexa_truthy(hexa_eq(esc, hexa_str("n")))) {
                                                    s = hexa_add(s, hexa_str("\n"));
                                                } else {
                                                    if (hexa_truthy(hexa_eq(esc, hexa_str("t")))) {
                                                        s = hexa_add(s, hexa_str("\t"));
                                                    } else {
                                                        if (hexa_truthy(hexa_eq(esc, hexa_str("r")))) {
                                                            s = hexa_add(s, hexa_str("\r"));
                                                        } else {
                                                            if (hexa_truthy(hexa_eq(esc, hexa_str("\\")))) {
                                                                s = hexa_add(s, hexa_str("\\"));
                                                            } else {
                                                                if (hexa_truthy(hexa_eq(esc, hexa_str("\"")))) {
                                                                    s = hexa_add(s, hexa_str("\""));
                                                                } else {
                                                                    if (hexa_truthy(hexa_eq(esc, hexa_str("0")))) {
                                                                        s = hexa_add(s, hexa_str(""));
                                                                    } else {
                                                                        s = hexa_add(s, hexa_to_string(esc));
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                                pos = hexa_add(pos, hexa_int(1));
                                                col = hexa_add(col, hexa_int(1));
                                            }
                                        } else {
                                            s = hexa_add(s, hexa_to_string(c));
                                            pos = hexa_add(pos, hexa_int(1));
                                            if (hexa_truthy(hexa_eq(c, hexa_str("\n")))) {
                                                line = hexa_add(line, hexa_int(1));
                                                col = hexa_int(1);
                                            } else {
                                                col = hexa_add(col, hexa_int(1));
                                            }
                                        }
                                    }
                                }
                                tokens = hexa_array_push(tokens, Token(hexa_str("StringLit"), s, line, start_col));
                            } else {
                                if (hexa_truthy(hexa_eq(ch, hexa_str("'")))) {
                                    HexaVal start_col = col;
                                    pos = hexa_add(pos, hexa_int(1));
                                    col = hexa_add(col, hexa_int(1));
                                    HexaVal ch_val = hexa_str("");
                                    if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((pos).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, pos), hexa_str("\\")))))) {
                                        pos = hexa_add(pos, hexa_int(1));
                                        col = hexa_add(col, hexa_int(1));
                                        if (hexa_truthy(hexa_bool((pos).i < (total).i))) {
                                            HexaVal esc = hexa_index_get(chars, pos);
                                            if (hexa_truthy(hexa_eq(esc, hexa_str("n")))) {
                                                ch_val = hexa_str("\n");
                                            } else {
                                                if (hexa_truthy(hexa_eq(esc, hexa_str("t")))) {
                                                    ch_val = hexa_str("\t");
                                                } else {
                                                    if (hexa_truthy(hexa_eq(esc, hexa_str("r")))) {
                                                        ch_val = hexa_str("\r");
                                                    } else {
                                                        if (hexa_truthy(hexa_eq(esc, hexa_str("\\")))) {
                                                            ch_val = hexa_str("\\");
                                                        } else {
                                                            if (hexa_truthy(hexa_eq(esc, hexa_str("'")))) {
                                                                ch_val = hexa_str("'");
                                                            } else {
                                                                if (hexa_truthy(hexa_eq(esc, hexa_str("0")))) {
                                                                    ch_val = hexa_str("");
                                                                } else {
                                                                    ch_val = hexa_to_string(esc);
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                            pos = hexa_add(pos, hexa_int(1));
                                            col = hexa_add(col, hexa_int(1));
                                        }
                                    } else {
                                        if (hexa_truthy(hexa_bool((pos).i < (total).i))) {
                                            ch_val = hexa_to_string(hexa_index_get(chars, pos));
                                            pos = hexa_add(pos, hexa_int(1));
                                            col = hexa_add(col, hexa_int(1));
                                        }
                                    }
                                    if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((pos).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, pos), hexa_str("'")))))) {
                                        pos = hexa_add(pos, hexa_int(1));
                                        col = hexa_add(col, hexa_int(1));
                                    }
                                    tokens = hexa_array_push(tokens, Token(hexa_str("CharLit"), ch_val, line, start_col));
                                } else {
                                    HexaVal start_col = col;
                                    if (hexa_truthy(hexa_eq(ch, hexa_str("+")))) {
                                        tokens = hexa_array_push(tokens, Token(hexa_str("Plus"), hexa_str("+"), line, start_col));
                                        pos = hexa_add(pos, hexa_int(1));
                                        col = hexa_add(col, hexa_int(1));
                                    } else {
                                        if (hexa_truthy(hexa_eq(ch, hexa_str("-")))) {
                                            if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_add(pos, hexa_int(1))).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, hexa_add(pos, hexa_int(1))), hexa_str(">")))))) {
                                                tokens = hexa_array_push(tokens, Token(hexa_str("Arrow"), hexa_str("->"), line, start_col));
                                                pos = hexa_add(pos, hexa_int(2));
                                                col = hexa_add(col, hexa_int(2));
                                            } else {
                                                tokens = hexa_array_push(tokens, Token(hexa_str("Minus"), hexa_str("-"), line, start_col));
                                                pos = hexa_add(pos, hexa_int(1));
                                                col = hexa_add(col, hexa_int(1));
                                            }
                                        } else {
                                            if (hexa_truthy(hexa_eq(ch, hexa_str("*")))) {
                                                if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_add(pos, hexa_int(1))).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, hexa_add(pos, hexa_int(1))), hexa_str("*")))))) {
                                                    tokens = hexa_array_push(tokens, Token(hexa_str("Power"), hexa_str("**"), line, start_col));
                                                    pos = hexa_add(pos, hexa_int(2));
                                                    col = hexa_add(col, hexa_int(2));
                                                } else {
                                                    tokens = hexa_array_push(tokens, Token(hexa_str("Star"), hexa_str("*"), line, start_col));
                                                    pos = hexa_add(pos, hexa_int(1));
                                                    col = hexa_add(col, hexa_int(1));
                                                }
                                            } else {
                                                if (hexa_truthy(hexa_eq(ch, hexa_str("/")))) {
                                                    tokens = hexa_array_push(tokens, Token(hexa_str("Slash"), hexa_str("/"), line, start_col));
                                                    pos = hexa_add(pos, hexa_int(1));
                                                    col = hexa_add(col, hexa_int(1));
                                                } else {
                                                    if (hexa_truthy(hexa_eq(ch, hexa_str("%")))) {
                                                        tokens = hexa_array_push(tokens, Token(hexa_str("Percent"), hexa_str("%"), line, start_col));
                                                        pos = hexa_add(pos, hexa_int(1));
                                                        col = hexa_add(col, hexa_int(1));
                                                    } else {
                                                        if (hexa_truthy(hexa_eq(ch, hexa_str("=")))) {
                                                            if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_add(pos, hexa_int(1))).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, hexa_add(pos, hexa_int(1))), hexa_str("=")))))) {
                                                                tokens = hexa_array_push(tokens, Token(hexa_str("EqEq"), hexa_str("=="), line, start_col));
                                                                pos = hexa_add(pos, hexa_int(2));
                                                                col = hexa_add(col, hexa_int(2));
                                                            } else {
                                                                tokens = hexa_array_push(tokens, Token(hexa_str("Eq"), hexa_str("="), line, start_col));
                                                                pos = hexa_add(pos, hexa_int(1));
                                                                col = hexa_add(col, hexa_int(1));
                                                            }
                                                        } else {
                                                            if (hexa_truthy(hexa_eq(ch, hexa_str("!")))) {
                                                                if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_add(pos, hexa_int(1))).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, hexa_add(pos, hexa_int(1))), hexa_str("=")))))) {
                                                                    tokens = hexa_array_push(tokens, Token(hexa_str("NotEq"), hexa_str("!="), line, start_col));
                                                                    pos = hexa_add(pos, hexa_int(2));
                                                                    col = hexa_add(col, hexa_int(2));
                                                                } else {
                                                                    tokens = hexa_array_push(tokens, Token(hexa_str("Not"), hexa_str("!"), line, start_col));
                                                                    pos = hexa_add(pos, hexa_int(1));
                                                                    col = hexa_add(col, hexa_int(1));
                                                                }
                                                            } else {
                                                                if (hexa_truthy(hexa_eq(ch, hexa_str("<")))) {
                                                                    if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_add(pos, hexa_int(1))).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, hexa_add(pos, hexa_int(1))), hexa_str("=")))))) {
                                                                        tokens = hexa_array_push(tokens, Token(hexa_str("LtEq"), hexa_str("<="), line, start_col));
                                                                        pos = hexa_add(pos, hexa_int(2));
                                                                        col = hexa_add(col, hexa_int(2));
                                                                    } else {
                                                                        tokens = hexa_array_push(tokens, Token(hexa_str("Lt"), hexa_str("<"), line, start_col));
                                                                        pos = hexa_add(pos, hexa_int(1));
                                                                        col = hexa_add(col, hexa_int(1));
                                                                    }
                                                                } else {
                                                                    if (hexa_truthy(hexa_eq(ch, hexa_str(">")))) {
                                                                        if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_add(pos, hexa_int(1))).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, hexa_add(pos, hexa_int(1))), hexa_str("=")))))) {
                                                                            tokens = hexa_array_push(tokens, Token(hexa_str("GtEq"), hexa_str(">="), line, start_col));
                                                                            pos = hexa_add(pos, hexa_int(2));
                                                                            col = hexa_add(col, hexa_int(2));
                                                                        } else {
                                                                            tokens = hexa_array_push(tokens, Token(hexa_str("Gt"), hexa_str(">"), line, start_col));
                                                                            pos = hexa_add(pos, hexa_int(1));
                                                                            col = hexa_add(col, hexa_int(1));
                                                                        }
                                                                    } else {
                                                                        if (hexa_truthy(hexa_eq(ch, hexa_str("&")))) {
                                                                            if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_add(pos, hexa_int(1))).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, hexa_add(pos, hexa_int(1))), hexa_str("&")))))) {
                                                                                tokens = hexa_array_push(tokens, Token(hexa_str("And"), hexa_str("&&"), line, start_col));
                                                                                pos = hexa_add(pos, hexa_int(2));
                                                                                col = hexa_add(col, hexa_int(2));
                                                                            } else {
                                                                                tokens = hexa_array_push(tokens, Token(hexa_str("BitAnd"), hexa_str("&"), line, start_col));
                                                                                pos = hexa_add(pos, hexa_int(1));
                                                                                col = hexa_add(col, hexa_int(1));
                                                                            }
                                                                        } else {
                                                                            if (hexa_truthy(hexa_eq(ch, hexa_str("|")))) {
                                                                                if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_add(pos, hexa_int(1))).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, hexa_add(pos, hexa_int(1))), hexa_str("|")))))) {
                                                                                    tokens = hexa_array_push(tokens, Token(hexa_str("Or"), hexa_str("||"), line, start_col));
                                                                                    pos = hexa_add(pos, hexa_int(2));
                                                                                    col = hexa_add(col, hexa_int(2));
                                                                                } else {
                                                                                    tokens = hexa_array_push(tokens, Token(hexa_str("BitOr"), hexa_str("|"), line, start_col));
                                                                                    pos = hexa_add(pos, hexa_int(1));
                                                                                    col = hexa_add(col, hexa_int(1));
                                                                                }
                                                                            } else {
                                                                                if (hexa_truthy(hexa_eq(ch, hexa_str("^")))) {
                                                                                    if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_add(pos, hexa_int(1))).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, hexa_add(pos, hexa_int(1))), hexa_str("^")))))) {
                                                                                        tokens = hexa_array_push(tokens, Token(hexa_str("Xor"), hexa_str("^^"), line, start_col));
                                                                                        pos = hexa_add(pos, hexa_int(2));
                                                                                        col = hexa_add(col, hexa_int(2));
                                                                                    } else {
                                                                                        tokens = hexa_array_push(tokens, Token(hexa_str("BitXor"), hexa_str("^"), line, start_col));
                                                                                        pos = hexa_add(pos, hexa_int(1));
                                                                                        col = hexa_add(col, hexa_int(1));
                                                                                    }
                                                                                } else {
                                                                                    if (hexa_truthy(hexa_eq(ch, hexa_str("~")))) {
                                                                                        tokens = hexa_array_push(tokens, Token(hexa_str("BitNot"), hexa_str("~"), line, start_col));
                                                                                        pos = hexa_add(pos, hexa_int(1));
                                                                                        col = hexa_add(col, hexa_int(1));
                                                                                    } else {
                                                                                        if (hexa_truthy(hexa_eq(ch, hexa_str("?")))) {
                                                                                            if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_add(pos, hexa_int(1))).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, hexa_add(pos, hexa_int(1))), hexa_str("?")))))) {
                                                                                                tokens = hexa_array_push(tokens, Token(hexa_str("NullCoal"), hexa_str("??"), line, start_col));
                                                                                                pos = hexa_add(pos, hexa_int(2));
                                                                                                col = hexa_add(col, hexa_int(2));
                                                                                            } else {
                                                                                                tokens = hexa_array_push(tokens, Token(hexa_str("Question"), hexa_str("?"), line, start_col));
                                                                                                pos = hexa_add(pos, hexa_int(1));
                                                                                                col = hexa_add(col, hexa_int(1));
                                                                                            }
                                                                                        } else {
                                                                                        if (hexa_truthy(hexa_eq(ch, hexa_str("@")))) {
                                                                                            tokens = hexa_array_push(tokens, Token(hexa_str("At"), hexa_str("@"), line, start_col));
                                                                                            pos = hexa_add(pos, hexa_int(1));
                                                                                            col = hexa_add(col, hexa_int(1));
                                                                                        } else {
                                                                                            if (hexa_truthy(hexa_eq(ch, hexa_str(":")))) {
                                                                                                if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_add(pos, hexa_int(1))).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, hexa_add(pos, hexa_int(1))), hexa_str("=")))))) {
                                                                                                    tokens = hexa_array_push(tokens, Token(hexa_str("ColonEq"), hexa_str(":="), line, start_col));
                                                                                                    pos = hexa_add(pos, hexa_int(2));
                                                                                                    col = hexa_add(col, hexa_int(2));
                                                                                                } else {
                                                                                                    if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_add(pos, hexa_int(1))).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, hexa_add(pos, hexa_int(1))), hexa_str(":")))))) {
                                                                                                        tokens = hexa_array_push(tokens, Token(hexa_str("ColonColon"), hexa_str("::"), line, start_col));
                                                                                                        pos = hexa_add(pos, hexa_int(2));
                                                                                                        col = hexa_add(col, hexa_int(2));
                                                                                                    } else {
                                                                                                        tokens = hexa_array_push(tokens, Token(hexa_str("Colon"), hexa_str(":"), line, start_col));
                                                                                                        pos = hexa_add(pos, hexa_int(1));
                                                                                                        col = hexa_add(col, hexa_int(1));
                                                                                                    }
                                                                                                }
                                                                                            } else {
                                                                                                if (hexa_truthy(hexa_eq(ch, hexa_str(".")))) {
                                                                                                    if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_add(pos, hexa_int(1))).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, hexa_add(pos, hexa_int(1))), hexa_str(".")))))) {
                                                                                                        if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_add(pos, hexa_int(2))).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, hexa_add(pos, hexa_int(2))), hexa_str("=")))))) {
                                                                                                            tokens = hexa_array_push(tokens, Token(hexa_str("DotDotEq"), hexa_str("..="), line, start_col));
                                                                                                            pos = hexa_add(pos, hexa_int(3));
                                                                                                            col = hexa_add(col, hexa_int(3));
                                                                                                        } else {
                                                                                                            tokens = hexa_array_push(tokens, Token(hexa_str("DotDot"), hexa_str(".."), line, start_col));
                                                                                                            pos = hexa_add(pos, hexa_int(2));
                                                                                                            col = hexa_add(col, hexa_int(2));
                                                                                                        }
                                                                                                    } else {
                                                                                                        tokens = hexa_array_push(tokens, Token(hexa_str("Dot"), hexa_str("."), line, start_col));
                                                                                                        pos = hexa_add(pos, hexa_int(1));
                                                                                                        col = hexa_add(col, hexa_int(1));
                                                                                                    }
                                                                                                } else {
                                                                                                    if (hexa_truthy(hexa_eq(ch, hexa_str("(")))) {
                                                                                                        tokens = hexa_array_push(tokens, Token(hexa_str("LParen"), hexa_str("("), line, start_col));
                                                                                                        pos = hexa_add(pos, hexa_int(1));
                                                                                                        col = hexa_add(col, hexa_int(1));
                                                                                                    } else {
                                                                                                        if (hexa_truthy(hexa_eq(ch, hexa_str(")")))) {
                                                                                                            tokens = hexa_array_push(tokens, Token(hexa_str("RParen"), hexa_str(")"), line, start_col));
                                                                                                            pos = hexa_add(pos, hexa_int(1));
                                                                                                            col = hexa_add(col, hexa_int(1));
                                                                                                        } else {
                                                                                                            if (hexa_truthy(hexa_eq(ch, hexa_str("{")))) {
                                                                                                                tokens = hexa_array_push(tokens, Token(hexa_str("LBrace"), hexa_str("{"), line, start_col));
                                                                                                                pos = hexa_add(pos, hexa_int(1));
                                                                                                                col = hexa_add(col, hexa_int(1));
                                                                                                            } else {
                                                                                                                if (hexa_truthy(hexa_eq(ch, hexa_str("}")))) {
                                                                                                                    tokens = hexa_array_push(tokens, Token(hexa_str("RBrace"), hexa_str("}"), line, start_col));
                                                                                                                    pos = hexa_add(pos, hexa_int(1));
                                                                                                                    col = hexa_add(col, hexa_int(1));
                                                                                                                } else {
                                                                                                                    if (hexa_truthy(hexa_eq(ch, hexa_str("[")))) {
                                                                                                                        tokens = hexa_array_push(tokens, Token(hexa_str("LBracket"), hexa_str("["), line, start_col));
                                                                                                                        pos = hexa_add(pos, hexa_int(1));
                                                                                                                        col = hexa_add(col, hexa_int(1));
                                                                                                                    } else {
                                                                                                                        if (hexa_truthy(hexa_eq(ch, hexa_str("]")))) {
                                                                                                                            tokens = hexa_array_push(tokens, Token(hexa_str("RBracket"), hexa_str("]"), line, start_col));
                                                                                                                            pos = hexa_add(pos, hexa_int(1));
                                                                                                                            col = hexa_add(col, hexa_int(1));
                                                                                                                        } else {
                                                                                                                            if (hexa_truthy(hexa_eq(ch, hexa_str(",")))) {
                                                                                                                                tokens = hexa_array_push(tokens, Token(hexa_str("Comma"), hexa_str(","), line, start_col));
                                                                                                                                pos = hexa_add(pos, hexa_int(1));
                                                                                                                                col = hexa_add(col, hexa_int(1));
                                                                                                                            } else {
                                                                                                                                if (hexa_truthy(hexa_eq(ch, hexa_str(";")))) {
                                                                                                                                    tokens = hexa_array_push(tokens, Token(hexa_str("Semicolon"), hexa_str(";"), line, start_col));
                                                                                                                                    pos = hexa_add(pos, hexa_int(1));
                                                                                                                                    col = hexa_add(col, hexa_int(1));
                                                                                                                                } else {
                                                                                                                                    if (hexa_truthy(hexa_eq(ch, hexa_str("@")))) {
                                                                                                                                        pos = hexa_add(pos, hexa_int(1));
                                                                                                                                        col = hexa_add(col, hexa_int(1));
                                                                                                                                        HexaVal attr_name = hexa_str("");
                                                                                                                                        while (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((pos).i < (total).i)) && hexa_truthy(is_ident_char(hexa_index_get(chars, pos)))))) {
                                                                                                                                            attr_name = hexa_add(attr_name, hexa_to_string(hexa_index_get(chars, pos)));
                                                                                                                                            pos = hexa_add(pos, hexa_int(1));
                                                                                                                                            col = hexa_add(col, hexa_int(1));
                                                                                                                                        }
                                                                                                                                        tokens = hexa_array_push(tokens, Token(hexa_str("Attribute"), attr_name, line, start_col));
                                                                                                                                    } else {
                                                                                                                                        if (hexa_truthy(hexa_eq(ch, hexa_str("#")))) {
                                                                                                                                            if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool((hexa_add(pos, hexa_int(1))).i < (total).i)) && hexa_truthy(hexa_eq(hexa_index_get(chars, hexa_add(pos, hexa_int(1))), hexa_str("{")))))) {
                                                                                                                                                tokens = hexa_array_push(tokens, Token(hexa_str("HashLBrace"), hexa_str("#{"), line, start_col));
                                                                                                                                                pos = hexa_add(pos, hexa_int(2));
                                                                                                                                                col = hexa_add(col, hexa_int(2));
                                                                                                                                            } else {
                                                                                                                                                pos = hexa_add(pos, hexa_int(1));
                                                                                                                                                col = hexa_add(col, hexa_int(1));
                                                                                                                                            }
                                                                                                                                        } else {
                                                                                                                                            pos = hexa_add(pos, hexa_int(1));
                                                                                                                                            col = hexa_add(col, hexa_int(1));
                                                                                                                                        }
                                                                                                                                    }
                                                                                                                                }
                                                                                                                            }
                                                                                                                        }
                                                                                                                    }
                                                                                                                }
                                                                                                            }
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    tokens = hexa_array_push(tokens, Token(hexa_str("Eof"), hexa_str(""), line, col));
    return tokens;
    return hexa_void();
}


HexaVal count_kind(HexaVal tokens, HexaVal kind) {
    HexaVal count = hexa_int(0);
    {
        HexaVal __iter_arr = tokens;
        for (int __fi = 0; __fi < hexa_len(__iter_arr); __fi++) {
            HexaVal t = hexa_array_get(__iter_arr, __fi);
            if (hexa_truthy(hexa_eq(hexa_map_get(t, "kind"), kind))) {
                count = hexa_add(count, hexa_int(1));
            }
        }
    }
    return count;
    return hexa_void();
}


int main() {
    return 0;
}
