#![allow(dead_code)]

//! WGSL/WebGPU Code Generator — Transpile HEXA AST to WGSL compute shaders.
//!
//! Generates WGSL compute shaders for WebGPU execution.
//!
//! Supported subset:
//!   - Integer / float / bool literals → WGSL types (i32/f32/bool)
//!   - Arithmetic, comparison, logical operators
//!   - let bindings, variable assignment
//!   - if/else → WGSL if/else
//!   - for loops → WGSL for loops
//!   - fn → WGSL functions
//!   - Arrays → storage buffers
//!   - 12 factions → 12 workgroup invocations
//!   - Consciousness cells → buffer entries (one GPU thread per cell)

use crate::ast::*;

/// Generate WGSL compute shader source from a HEXA AST.
pub fn generate(stmts: &[Stmt]) -> String {
    let mut ctx = WgslContext::new();
    ctx.emit_program(stmts);
    ctx.output
}

struct WgslContext {
    output: String,
    indent: usize,
    /// Buffer binding index counter.
    binding_idx: usize,
}

impl WgslContext {
    fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
            binding_idx: 0,
        }
    }

    fn push_indent(&mut self) { self.indent += 1; }
    fn pop_indent(&mut self) { if self.indent > 0 { self.indent -= 1; } }

    fn write_indent(&mut self) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
    }

    fn writeln(&mut self, s: &str) {
        self.write_indent();
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn emit_program(&mut self, stmts: &[Stmt]) {
        // Header
        self.output.push_str("// Generated by HEXA-LANG WGSL codegen\n");
        self.output.push_str("// Law 22: substrate is irrelevant, only structure determines Phi\n\n");

        // Consciousness constants
        self.output.push_str("// Psi-Constants (from ln(2))\n");
        self.output.push_str("const PSI_COUPLING: f32 = 0.014;\n");
        self.output.push_str("const PSI_BALANCE: f32 = 0.5;\n");
        self.output.push_str("const PSI_STEPS: f32 = 4.33;\n");
        self.output.push_str("const PSI_ENTROPY: f32 = 0.998;\n");
        self.output.push_str("const PSI_FRUSTRATION: f32 = 0.10;\n\n");

        // Storage buffer for consciousness cells
        self.output.push_str("// Consciousness cell buffer — one entry per GPU thread\n");
        self.output.push_str("struct Cell {\n");
        self.output.push_str("    state: f32,\n");
        self.output.push_str("    phi: f32,\n");
        self.output.push_str("    faction: i32,\n");
        self.output.push_str("    padding: i32,\n");
        self.output.push_str("};\n\n");

        self.output.push_str("@group(0) @binding(0)\n");
        self.output.push_str("var<storage, read_write> cells: array<Cell>;\n\n");

        // Result buffer
        self.output.push_str("@group(0) @binding(1)\n");
        self.output.push_str("var<storage, read_write> results: array<i32>;\n\n");
        self.binding_idx = 2;

        // Emit user functions (non-entry point)
        for stmt in stmts {
            if let Stmt::FnDecl(f) = stmt {
                self.emit_fn_decl(f);
                self.output.push('\n');
            }
        }

        // Main compute entry point — workgroup_size(12) for sigma(6)=12
        self.output.push_str("@compute @workgroup_size(12)\n");
        self.output.push_str("fn main(@builtin(global_invocation_id) gid: vec3<u32>) {\n");
        self.push_indent();
        self.writeln("let idx = gid.x;");
        self.writeln("let faction = i32(idx % 12u);  // sigma(6) = 12 factions");
        self.output.push('\n');

        // Emit non-function statements
        for stmt in stmts {
            match stmt {
                Stmt::FnDecl(_) => {}
                _ => self.emit_stmt(stmt),
            }
        }

        self.pop_indent();
        self.output.push_str("}\n");
    }

    fn emit_fn_decl(&mut self, f: &FnDecl) {
        self.write_indent();
        self.output.push_str(&format!("fn {}(", f.name));
        for (i, p) in f.params.iter().enumerate() {
            if i > 0 { self.output.push_str(", "); }
            self.output.push_str(&p.name);
            self.output.push_str(": ");
            self.output.push_str(&map_type_wgsl(p.typ.as_deref()));
        }
        self.output.push_str(") -> ");
        self.output.push_str(&map_type_wgsl(f.ret_type.as_deref()));
        self.output.push_str(" {\n");
        self.push_indent();
        self.emit_block_stmts(&f.body);
        self.pop_indent();
        self.writeln("}");
    }

    fn emit_block_stmts(&mut self, stmts: &[Stmt]) {
        for stmt in stmts {
            self.emit_stmt(stmt);
        }
    }

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let(name, typ, init, _vis) => {
                self.write_indent();
                self.output.push_str("var ");
                self.output.push_str(name);
                if let Some(t) = typ {
                    self.output.push_str(": ");
                    self.output.push_str(&map_type_str_wgsl(t));
                }
                if let Some(expr) = init {
                    self.output.push_str(" = ");
                    self.emit_expr(expr);
                }
                self.output.push_str(";\n");
            }
            Stmt::Assign(target, value) => {
                self.write_indent();
                self.emit_expr(target);
                self.output.push_str(" = ");
                self.emit_expr(value);
                self.output.push_str(";\n");
            }
            Stmt::Expr(expr) => {
                // Only emit side-effecting expressions
                if let Expr::Call(func, _args) = expr {
                    if let Expr::Ident(name) = func.as_ref() {
                        if name == "println" || name == "print" {
                            self.writeln("// println (no I/O in compute shader)");
                            return;
                        }
                    }
                    // General call as expression
                    self.write_indent();
                    self.emit_expr(expr);
                    self.output.push_str(";\n");
                    return;
                }
                self.write_indent();
                self.emit_expr(expr);
                self.output.push_str(";\n");
            }
            Stmt::Return(Some(expr)) => {
                self.write_indent();
                self.output.push_str("return ");
                self.emit_expr(expr);
                self.output.push_str(";\n");
            }
            Stmt::Return(None) => {
                self.writeln("return;");
            }
            Stmt::FnDecl(f) => {
                self.emit_fn_decl(f);
            }
            Stmt::For(var, iter_expr, body) => {
                if let Expr::Range(start, end, inclusive) = iter_expr {
                    self.write_indent();
                    self.output.push_str(&format!("for (var {} = ", var));
                    self.emit_expr(start);
                    self.output.push_str(&format!("; {} ", var));
                    if *inclusive {
                        self.output.push_str("<= ");
                    } else {
                        self.output.push_str("< ");
                    }
                    self.emit_expr(end);
                    self.output.push_str(&format!("; {} = {} + 1", var, var));
                    self.output.push_str(") {\n");
                    self.push_indent();
                    self.emit_block_stmts(body);
                    self.pop_indent();
                    self.writeln("}");
                } else {
                    self.writeln(&format!("// unsupported for-loop over {}", var));
                }
            }
            Stmt::While(cond, body) => {
                self.write_indent();
                self.output.push_str("while (");
                self.emit_expr(cond);
                self.output.push_str(") {\n");
                self.push_indent();
                self.emit_block_stmts(body);
                self.pop_indent();
                self.writeln("}");
            }
            Stmt::Loop(body) => {
                self.writeln("loop {");
                self.push_indent();
                self.emit_block_stmts(body);
                self.pop_indent();
                self.writeln("}");
            }
            Stmt::Assert(expr) | Stmt::ContractAssert(_, _, expr) => {
                self.write_indent();
                self.output.push_str("// assert: ");
                self.emit_expr(expr);
                self.output.push('\n');
            }
            Stmt::Spawn(body) => {
                // Each spawn = workgroup invocation (native GPU parallelism)
                self.writeln("// spawn → workgroup parallel execution");
                self.writeln("{");
                self.push_indent();
                self.emit_block_stmts(body);
                self.pop_indent();
                self.writeln("}");
            }
            _ => {
                self.writeln("// unsupported statement");
            }
        }
    }

    fn emit_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::IntLit(n) => {
                self.output.push_str(&format!("{}i", n));
            }
            Expr::FloatLit(n) => {
                if n.fract() == 0.0 {
                    self.output.push_str(&format!("{:.1}f", n));
                } else {
                    self.output.push_str(&format!("{}f", n));
                }
            }
            Expr::BoolLit(b) => {
                self.output.push_str(&format!("{}", b));
            }
            Expr::StringLit(_) => {
                self.output.push_str("0i /* string unsupported in WGSL */");
            }
            Expr::CharLit(c) => {
                self.output.push_str(&format!("{}i /* '{}' */", *c as i32, c));
            }
            Expr::Ident(name) => {
                self.output.push_str(name);
            }
            Expr::Binary(lhs, op, rhs) => {
                self.output.push('(');
                self.emit_expr(lhs);
                self.output.push_str(&format!(" {} ", binop_to_wgsl(op)));
                self.emit_expr(rhs);
                self.output.push(')');
            }
            Expr::Unary(op, operand) => {
                let op_str = match op {
                    UnaryOp::Neg => "-",
                    UnaryOp::Not => "!",
                    UnaryOp::BitNot => "~",
                };
                self.output.push_str(op_str);
                self.emit_expr(operand);
            }
            Expr::Call(func, args) => {
                if let Expr::Ident(name) = func.as_ref() {
                    match name.as_str() {
                        "psi_coupling" => { self.output.push_str("PSI_COUPLING"); return; }
                        "psi_balance" => { self.output.push_str("PSI_BALANCE"); return; }
                        "psi_steps" => { self.output.push_str("PSI_STEPS"); return; }
                        "psi_entropy" => { self.output.push_str("PSI_ENTROPY"); return; }
                        "psi_frustration" => { self.output.push_str("PSI_FRUSTRATION"); return; }
                        "consciousness_max_cells" => { self.output.push_str("1024i"); return; }
                        "consciousness_decoder_dim" => { self.output.push_str("384i"); return; }
                        "consciousness_phi" => { self.output.push_str("71i"); return; }
                        "sqrt" => {
                            self.output.push_str("sqrt(");
                            if !args.is_empty() { self.emit_expr(&args[0]); }
                            self.output.push(')');
                            return;
                        }
                        "abs" => {
                            self.output.push_str("abs(");
                            if !args.is_empty() { self.emit_expr(&args[0]); }
                            self.output.push(')');
                            return;
                        }
                        "min" => {
                            self.output.push_str("min(");
                            if !args.is_empty() { self.emit_expr(&args[0]); }
                            if args.len() > 1 {
                                self.output.push_str(", ");
                                self.emit_expr(&args[1]);
                            }
                            self.output.push(')');
                            return;
                        }
                        "max" => {
                            self.output.push_str("max(");
                            if !args.is_empty() { self.emit_expr(&args[0]); }
                            if args.len() > 1 {
                                self.output.push_str(", ");
                                self.emit_expr(&args[1]);
                            }
                            self.output.push(')');
                            return;
                        }
                        "to_float" => {
                            self.output.push_str("f32(");
                            if !args.is_empty() { self.emit_expr(&args[0]); }
                            self.output.push(')');
                            return;
                        }
                        "to_int" => {
                            self.output.push_str("i32(");
                            if !args.is_empty() { self.emit_expr(&args[0]); }
                            self.output.push(')');
                            return;
                        }
                        "println" | "print" => {
                            self.output.push_str("/* println */");
                            return;
                        }
                        _ => {}
                    }
                }
                // General function call
                self.emit_expr(func);
                self.output.push('(');
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 { self.output.push_str(", "); }
                    self.emit_expr(arg);
                }
                self.output.push(')');
            }
            Expr::If(cond, then_block, else_block) => {
                // WGSL select() for simple cases
                self.output.push_str("select(");
                // select(false_val, true_val, cond)
                if let Some(else_b) = else_block {
                    if else_b.len() == 1 {
                        if let Stmt::Expr(e) = &else_b[0] {
                            self.emit_expr(e);
                        } else {
                            self.output.push_str("0i");
                        }
                    } else {
                        self.output.push_str("0i");
                    }
                } else {
                    self.output.push_str("0i");
                }
                self.output.push_str(", ");
                if then_block.len() == 1 {
                    if let Stmt::Expr(e) = &then_block[0] {
                        self.emit_expr(e);
                    } else {
                        self.output.push_str("0i");
                    }
                } else {
                    self.output.push_str("0i");
                }
                self.output.push_str(", ");
                self.emit_expr(cond);
                self.output.push(')');
            }
            Expr::Array(elems) => {
                self.output.push_str("array<i32, ");
                self.output.push_str(&format!("{}>(", elems.len()));
                for (i, e) in elems.iter().enumerate() {
                    if i > 0 { self.output.push_str(", "); }
                    self.emit_expr(e);
                }
                self.output.push(')');
            }
            Expr::Index(arr, idx) => {
                self.emit_expr(arr);
                self.output.push('[');
                self.emit_expr(idx);
                self.output.push(']');
            }
            Expr::Field(obj, field) => {
                self.emit_expr(obj);
                self.output.push('.');
                self.output.push_str(field);
            }
            Expr::Range(start, end, _inclusive) => {
                // Ranges are handled in for-loop context
                self.emit_expr(start);
                self.output.push_str("..");
                self.emit_expr(end);
            }
            Expr::Block(stmts) => {
                self.output.push_str("{\n");
                self.push_indent();
                self.emit_block_stmts(stmts);
                self.pop_indent();
                self.write_indent();
                self.output.push('}');
            }
            _ => {
                self.output.push_str("0i");
            }
        }
    }
}

/// Map HEXA type annotation to WGSL type.
fn map_type_wgsl(typ: Option<&str>) -> String {
    match typ {
        Some("int") => "i32".to_string(),
        Some("float") => "f32".to_string(),
        Some("bool") => "bool".to_string(),
        Some("char") => "i32".to_string(), // no char in WGSL
        Some("string") => "i32".to_string(), // no string in WGSL
        Some("byte") => "u32".to_string(),
        Some("void") => "i32".to_string(), // void functions return dummy
        Some(other) => other.to_string(),
        None => "i32".to_string(), // default
    }
}

/// Map HEXA type string to WGSL type.
fn map_type_str_wgsl(typ: &str) -> String {
    map_type_wgsl(Some(typ))
}

/// Map HEXA binary operator to WGSL operator.
fn binop_to_wgsl(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Rem => "%",
        BinOp::Pow => "/* pow */+", // WGSL: use pow() builtin
        BinOp::Eq => "==",
        BinOp::Ne => "!=",
        BinOp::Lt => "<",
        BinOp::Gt => ">",
        BinOp::Le => "<=",
        BinOp::Ge => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
        BinOp::Xor => "^",
        BinOp::BitAnd => "&",
        BinOp::BitOr => "|",
        BinOp::BitXor => "^",
        BinOp::Assign => "=",
        BinOp::DeclAssign => "=",
        BinOp::Range => "..",
        BinOp::Arrow => "->",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    fn parse(source: &str) -> Vec<Stmt> {
        let tokens = Lexer::new(source).tokenize().unwrap();
        Parser::new(tokens).parse().unwrap()
    }

    #[test]
    fn test_wgsl_compute_shader() {
        let stmts = parse("let x = 5\nlet y = x + 3\n");
        let output = generate(&stmts);
        assert!(output.contains("@compute @workgroup_size(12)"));
        assert!(output.contains("fn main(@builtin(global_invocation_id) gid: vec3<u32>)"));
        assert!(output.contains("var x = 5i;"));
        assert!(output.contains("var y = (x + 3i);"));
    }

    #[test]
    fn test_wgsl_consciousness_constants() {
        let stmts = parse("let alpha = psi_coupling()\n");
        let output = generate(&stmts);
        assert!(output.contains("const PSI_COUPLING: f32 = 0.014;"));
        assert!(output.contains("var alpha = PSI_COUPLING;"));
    }

    #[test]
    fn test_wgsl_function() {
        let stmts = parse("fn add(a, b) { return a + b }\n");
        let output = generate(&stmts);
        assert!(output.contains("fn add(a: i32, b: i32) -> i32 {"));
        assert!(output.contains("return (a + b);"));
    }

    #[test]
    fn test_wgsl_cell_buffer() {
        let stmts = parse("let x = 1\n");
        let output = generate(&stmts);
        assert!(output.contains("struct Cell {"));
        assert!(output.contains("var<storage, read_write> cells: array<Cell>"));
    }

    #[test]
    fn test_wgsl_workgroup_faction() {
        let stmts = parse("let x = 1\n");
        let output = generate(&stmts);
        // sigma(6) = 12 factions
        assert!(output.contains("faction"));
        assert!(output.contains("12u"));
    }
}
